[build]
    command = "gatsby build"
    publish = "public"

[functions]
    directory = "functions/"
    node_bundler = "esbuild"

[dev]
    port = 3000

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200



   