[build]
    command = "gatsby build"
    publish = "public"

[build.environment]
    NODE_VERSION = "12.13.0"

[dev]
    command = "gatsby develop"
    port = 8000

[[plugins]]
  package = "@netlify/plugin-gatsby"

[functions]
