[build]
    command = "gatsby build"
    publish = "public"
[dev]
    command = "gatsby develop"
    port = 8000

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200