[build]
    command = "gatsby build"
    functions = "functions/"
    publish = "public"


[dev]
    command = "gatsby develop"
    port = 8000

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
